# Section A – Conceptual Understanding

## A1. Why are NumPy arrays generally preferred over plain Python lists for numerical computation in AI/ML workloads? Mention at least two concrete reasons. [2 marks]

## Answer:
NumPy arrays are generally preferred over Python lists for numerical computation because they are faster and use memory more efficiently. NumPy provides vectorized operations, so we can perform calculations on many values at once without writing separate loops. It also supports mathematical and statistical operations directly, which makes it useful for handling large amounts of numerical data in AI/ML.

## A2. Explain vectorization. Why does replacing an explicit Python loop with a vectorized NumPy operation matter with large datasets? [2 marks]

## Answer:
Vectorization means performing an operation on the whole NumPy array at once instead of using a Python loop for each value. It is useful because NumPy can perform these operations faster and more efficiently. When the dataset is large, vectorization reduces the time needed for calculations and makes the program more efficient.



## A3. For compatible 2D arrays A and B, explain A * B vs A @ B. Describe one neural-network situation for each. [2 marks]

## Answer:
A * B performs element-wise multiplication, which means each element of A is multiplied by the corresponding element of B. A @ B performs matrix multiplication, where rows and columns are multiplied to produce a new matrix. In a neural network, * can be used for element-wise operations such as applying a mask, while @ is commonly used to multiply input data with a weight matrix.


## A4. What is broadcasting in NumPy? State the general rule used to decide whether arrays of different shapes can be combined element-wise. [2 marks]

## Answer:
Broadcasting is a NumPy feature that allows arrays with different shapes to be used together in element-wise operations. NumPy compares their shapes starting from the last dimension. The dimensions are compatible when they are equal or when one of them is 1. If the dimensions do not satisfy this rule, NumPy gives a shape error.

## A5. Explain flatten() vs ravel(). In a memory-constrained application processing large images, which would you prefer and why? [2 marks]

## Answer:
flatten() converts an array into a 1D array and always creates a new copy of the data. ravel() also converts an array into 1D, but it usually returns a view of the original array instead of making a copy. For a memory-constrained application working with large images, I would prefer ravel() because it usually uses less extra memory.

## A6. For a 2D array, explain axis=0 and axis=1 in an aggregation function such as np.sum() or np.mean(). Illustrate with a small example. [2 marks]

## Answer:
For a 2D array, axis=0 means the operation is performed column-wise, while axis=1 means it is performed row-wise


In [2]:
import numpy as np
arr = np.array([[1, 2],
                [3, 4]])
column_sum=np.sum(arr, axis=0)  
row_sum=np.sum(arr, axis=1)   
print(column_sum)
print(row_sum)
# So, axis=0 adds the values in each column and axis=1 adds the values in each row

[4 6]
[3 7]


## A7. Why is it important to normalize or standardize numerical features before training most ML models? Explain normalization vs standardization. [2 marks]

## Answer:
Normalization or standardization is important because features can have different ranges, which can affect the performance of an ML model. Normalization usually scales values to a fixed range such as 0 to 1. Standardization changes the values so that they have a mean of 0 and a standard deviation of 1. This helps the model handle different features more effectively

## A8. Why do functions such as np.nanmean() exist? What happens if np.mean() is used directly on data containing NaN? [2 marks]

## Answer:
np.nanmean() is used to calculate the mean while ignoring NaN values. If we use np.mean() directly on an array containing NaN, the result will usually be nan. Therefore, np.nanmean() is useful when the data contains missing values.


## A9. In the ML convention X.shape = (samples, features), explain how this extends to a batch of RGB images. Write the exact shape for 64 RGB images of size 128 × 128. [2 marks]

## Answer:
For normal ML data, X.shape = (samples, features) means the first dimension represents the number of samples and the second represents the features. For RGB images, we also need height, width, and 3 color channels. Therefore, 64 RGB images of size 128 × 128 have the shape (64, 128, 128, 3).



## A10. Why is reproducibility important during model development and experimentation? Refer to fixing a random seed with np.random.default_rng(seed). [2 marks]

## Answer:
Reproducibility means getting the same results when we run the same experiment again. Random operations can give different results each time, so fixing a seed makes the random values repeatable. For example, np.random.default_rng(seed) can be used with a fixed seed. This makes it easier to test, compare, and debug ML experiments.

# Section B – Predict the Output

## B1. Predict the exact output and/or resulting shape. Justify in one sentence. [2 marks]
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print((a + b).shape)

## predicted output:(3,3)
The array a has 3 elements in a single dimension, and array b has 3 rows and 1 column. NumPy uses broadcasting to add them, so the final output has the shape (3, 3).

In [2]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print((a + b).shape)

(3, 3)


## B2. Predict the output and/or shape. [2 marks]
x = np.arange(1, 7).reshape(2, 3)
print(x[:, 1])

## predicted output:[2 5]
Initially, np.arange(1, 7) creates a 1D array x with elements from 1 to 6. reshape(2, 3) changes the shape of the array to 2 rows and 3 columns. The first row will have 1, 2, 3 and the second row will have 4, 5, 6. Then, the slicing operation retrieves the elements from the second column, which are 2 and 5.

In [3]:
import numpy as np
x = np.arange(1, 7).reshape(2, 3)
print(x[:, 1])

[2 5]


## B3. Predict the output and/or shape. [2 marks]
arr = np.array([5, 10, 15, 20, 25])
print(arr[arr % 10 == 0])

## predicted output:[10,20]
arr % 10 checks each element in arr to see whether it is exactly divisible by 10. It returns the elements that are divisible by 10.

In [4]:
import numpy as np
arr = np.array([5, 10, 15, 20, 25])
print(arr[arr % 10 == 0])


[10 20]


## B4. Predict the output and/or shape. [2 marks]
m = np.array([[1, 2], [3, 4]])
print(m.T @ m)
## predicted output:
 [[10 14]
 [14 20]]
m.T converts the matrix m to its transpose matrix. @ is used for matrix multiplication, where m.T @ m multiplies the transpose matrix m.T with the original matrix m.

In [5]:
import numpy as np
m = np.array([[1, 2], [3, 4]])
print(m.T @ m)

[[10 14]
 [14 20]]


# Section C – Coding / Implementation


## C1. Given a 1D NumPy array of exam scores, use np.where() to produce labels 'P' (score >= 40) or 'F' (score < 40).

In [6]:
import numpy as np
exam_scores=np.array([80,75,39,90])
res=np.where(exam_scores>=40,'P','F')
print(res)

['P' 'P' 'F' 'P']


## Explanation: 
np.where() checks each score and gives P for scores greater than or equal to 40, otherwise it gives F.

## C2. Write a function standardize(x) that takes a 1D NumPy array and returns its z-score standardized version using only NumPy. 

In [7]:
import numpy as np
def standardize(x):
    mean=np.mean(x)
    standard_dev=np.std(x)
    return (x-mean)/standard_dev
x=np.array([25,35,10,45,40])
res=standardize(x)
print(res)

[-0.48349378  0.32232919 -1.69222822  1.12815215  0.72524067]


## Explanation: 
The np.mean() function calculates the mean and np.std() calculates the standard deviation of the array and converts each value into its z-score using (x - mean) / std.

## C3. Given two 2D NumPy arrays representing separate batches with the same number of features, combine them using an appropriate NumPy stacking function and print the resulting shape.

In [8]:
import numpy as np
batch1=np.array([[1,2,3],[4,5,6]])
batch2=np.array([[10,20,30],[40,50,60]])
res=np.vstack((batch1,batch2))
print(res.shape)

(4, 3)


## Explanation: 
np.vstack() combines the two arrays row-wise, so the resulting array has 4 rows and 3 columns

## C4. Given X with shape (100, 5), compute column-wise mean and standard deviation and standardize the matrix in one vectorized expression.

In [10]:
import numpy as np
X=np.random.rand(100,5)
mean=np.mean(X,axis=0)
std=np.std(X,axis=0)
standardize=(X-mean)/std
print("Mean:",mean)
print("Standard deviation:",std)
print("Standardized shape:",standardize.shape)


Mean: [0.53022951 0.55634843 0.48419171 0.46920947 0.49420699]
Standard deviation: [0.26817749 0.2879337  0.2758128  0.28294029 0.30572313]
Standardized shape: (100, 5)


## Explanation: 
axis=0 calculates the mean and standard deviation for each column. Then (X - mean) / std is used to standardize all the values in the array. Since NumPy performs these calculations on the complete array at once, it does not need a loop.

## C5. Implement y_pred = X @ w + b for a feature matrix X, weight vector w and bias b. Then compute MSE using y_true

In [1]:
import numpy as np

X = np.array([[1, 2],
              [3, 4],
              [5, 6]])

w = np.array([0.5, 1])
b = 2

y_true = np.array([4, 8, 10])

y_pred = X @ w + b

mse = np.mean((y_true - y_pred) ** 2)

print("Predicted values:", y_pred)
print("MSE:", mse)

Predicted values: [ 4.5  7.5 10.5]
MSE: 0.25


## Explanation:
X @ w performs matrix multiplication between the feature matrix and weight vector. Then b is added to get the predicted values. Finally, MSE is calculated by finding the mean of the squared differences between the actual values y_true and predicted values y_pred.

## C6. Using np.random.default_rng() with a fixed seed, generate 10 samples and 3 features from a normal distribution. Print the shape and confirm identical results with the same seed.

In [2]:
import numpy as np

rng1 = np.random.default_rng(42)
data1 = rng1.normal(size=(10, 3))

rng2 = np.random.default_rng(42)
data2 = rng2.normal(size=(10, 3))

print("Shape:", data1.shape)
print("Identical results:", np.array_equal(data1, data2))

Shape: (10, 3)
Identical results: True


## Explanation:
default_rng(42) creates a random number generator with a fixed seed. It generates 10 samples with 3 features, so the shape is (10, 3). Since both generators use the same seed, they produce the same random values, so the result is True.

## C7. Given a grayscale image as a 2D NumPy array with pixel values in [0, 255], normalize the values to [0, 1] using min-max normalization.

In [3]:
import numpy as np

image = np.array([[0, 50, 100],
                  [150, 200, 255]])

normalized = (image - image.min()) / (image.max() - image.min())

print(normalized)

[[0.         0.19607843 0.39215686]
 [0.58823529 0.78431373 1.        ]]


## Explanation:
First, the minimum and maximum pixel values are found from the image. Then the min-max formula is used to convert the pixel values from the range 0–255 to the range 0–1. The smallest value becomes 0 and the largest value becomes 1.

## C8. Given 4 RGB images of shape (28, 28, 3), stored as shape (4, 28, 28, 3), compute the average pixel value of each image across height, width and channels. State the axis argument and why.

In [4]:
import numpy as np

images = np.random.randint(0, 256, size=(4, 28, 28, 3))

average = np.mean(images, axis=(1, 2, 3))

print("Average pixel value of each image:", average)
print("Shape:", average.shape)

Average pixel value of each image: [128.77508503 129.01445578 128.02380952 130.26190476]
Shape: (4,)


## Explanation:
The shape of the images is (4, 28, 28, 3), where 4 represents the images, 28, 28 represent height and width, and 3 represents the RGB channels. I used axis=(1, 2, 3) because I want to calculate the average across the height, width and RGB channels while keeping each image separate. Therefore, the result contains one average value for each of the 4 images.

# Section D – Applied / Scenario-Based Problems

## D1. Data Preprocessing Pipeline

You are given a raw 1D or 2D NumPy array containing NaN values. Describe, step by step, the NumPy operations you would apply to:

(a) detect missing values,
(b) handle them appropriately and justify your strategy, and
(c) normalize or standardize the clean data before it is fed to a model.

Implement the full pipeline in code on a sample array of your own choosing, including at least one NaN.

## Answer:

- First, I would detect the missing values using `np.isnan()`.
- Then, I would handle the missing values by replacing each NaN with the mean of its column. This is useful because we can keep the data instead of removing the complete row.
- After handling the missing values, I would standardize the data using the mean and standard deviation of each column.

In [5]:
data = np.array([[10, 20],
                 [15, np.nan],
                 [30, 40]]) 

# (a) Detect missing values
missing = np.isnan(data)
print("Missing values:")
print(missing) 

Missing values:
[[False False]
 [False  True]
 [False False]]


In [6]:
# (b) Handle missing values using column mean
column_mean = np.nanmean(data, axis=0)
rows, cols = np.where(np.isnan(data))
data[rows, cols] = column_mean[cols]
print("After handling NaN:")
print(data)

After handling NaN:
[[10. 20.]
 [15. 30.]
 [30. 40.]]


In [7]:
# (c) Standardize the clean data
mean = np.mean(data, axis=0)
std = np.std(data, axis=0)
standardized_data = (data - mean) / std
print("Standardized data:")
print(standardized_data)

Standardized data:
[[-0.98058068 -1.22474487]
 [-0.39223227  0.        ]
 [ 1.37281295  1.22474487]]


## D2. Image Batch Understanding

1. Explain, with correct NumPy shapes, how a single RGB image differs from a batch of RGB images.

- A single RGB image of size 64 × 64 has the shape:


(64, 64, 3)


Here, 64 is the height, 64 is the width and 3 represents the RGB channels.

- A batch of 16 RGB images has the shape:


(16, 64, 64, 3)


Here, 16 represents the number of images.




## 2.Write code to create a dummy batch of 16 images of size 64 × 64 using random pixel values.

In [ ]:
images = np.random.randint(0, 256, size=(16, 64, 64, 3))
print(images.shape)

(16, 64, 64, 3)


## 3.Compute the average image of the batch, meaning the element-wise mean across all 16 images.

In [9]:
average_image = np.mean(images, axis=0)
print(average_image.shape)

(64, 64, 3)


## 4.State the shape of your result and explain why.

- Shape of the result: `(64, 64, 3)`
- **Justification:** axis=0 calculates the mean across the 16 images. Therefore, the image dimension is removed and one average value is produced for every pixel and RGB channel. The result is one average RGB image of shape (64, 64, 3).


## D3. Debug the Model Code

The following code contains more than one bug:

```python
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])  # shape (3, 2)
w = np.array([0.5, 1.0, 0.2])  # intended weight vector
b = 2.0
y_pred = X @ w + b
y_true = np.array([10, 20, 30])
mse = np.mean(y_true - y_pred ** 2)
```

Identify every bug. Explain, in terms of shapes and operator precedence, why each is a problem, and rewrite the corrected code.

**Bug 1 – Weight shape**

- X has shape (3, 2), so it has 2 features. Therefore, w should have 2 values.
- But w has 3 values, so `X @ w` gives a shape error.

**Bug 2 – MSE formula**

The given code is:

```python
mse = np.mean(y_true - y_pred ** 2)
```

- Here, `**` is calculated first. So it becomes `y_true - (y_pred ** 2)`.
- The correct MSE formula is:

```python
mse = np.mean((y_true - y_pred) ** 2)
```

In [10]:
#Corrected code:
import numpy as np
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])
w = np.array([0.5, 1.0])
b = 2.0
y_pred = X @ w + b
y_true = np.array([10, 20, 30])
mse = np.mean((y_true - y_pred) ** 2)
print(y_pred)
print(mse)

[4.5 6.  7.5]
244.16666666666666


# Section E – Bonus / Challenge

## E1. Per-Column Min–Max Normalization [5 marks]
Implement min-max normalization for a 2D feature matrix on a per-column (per-feature) basis, rather than using a single global min/max for the whole array. Your solution must be fully vectorized, with no explicit loops over rows or columns.

In [12]:
X = np.array([[10, 100],
              [20, 200],
              [30, 300],
              [40, 400]])
min_values = np.min(X, axis=0)
max_values = np.max(X, axis=0)
X_normalized = (X - min_values) / (max_values - min_values)
print(X_normalized)

[[0.         0.        ]
 [0.33333333 0.33333333]
 [0.66666667 0.66666667]
 [1.         1.        ]]


- Here, axis=0 calculates the minimum and maximum for each column separately.
- The operation is fully vectorized, so there are no explicit loops.

## E2. Three-Level Score Classification [5 marks]
Given a 1D array of exam scores, use a single vectorized expression (no if/else statements and no explicit loops) to classify each score as:
Fail (< 40), Average (40–70 inclusive), or Excellent (> 70).
Hint: You may need to nest or combine np.where() calls.

In [ ]:
scores = np.array([25, 40, 55, 70, 85, 95])
result = np.where(scores < 40, "Fail", np.where(scores <= 70, "Average", "Excellent"))
print(result)

['Fail' 'Average' 'Average' 'Average' 'Excellent' 'Excellent']


- This uses nested `np.where()` and is fully vectorized without loops or if/else statements.